
typeset -U path PATH
path=(${path:#/Users/marcokalz/Anaconda/anaconda3/bin})
path=(${path:#/Users/marcokalz/Anaconda/anaconda3/condabin})
path=(${path:#/Library/Frameworks/Python.framework/Versions/3.8/bin})
path=(${path:#/Library/Frameworks/Python.framework/Versions/3.8/bin/Users/*})
eval "$(/opt/homebrew/bin/brew shellenv)"
path+=("$HOME/bin")

# Added by `rbenv init` on Sa.  7 März 2026 07:03:59 CET
eval "$(rbenv init - --no-rehash zsh)"

# Homebrew Python 3.13: prefer generic python3/pip3 links from Apple Silicon Homebrew
path=("/opt/homebrew/opt/python@3.13/libexec/bin" $path)
typeset -U path PATH
