vscode:
  extensions:
    - github.vscode-github-actions
    - timonwong.shellcheck
    - redhat.vscode-yaml
    - davidanson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - quarto.quarto
    - eamodio.gitlens
    - ms-python.python
    - ms-toolsai.jupyter